spring:
  application:
    name: api-franchise
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

server:
  port: 8001
