spring:
  application:
    name: api-franchise
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://db:5432/franchise_db}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:postgres}

server:
  port: 8001
